name: Deploy Publication Layer

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Data Repo
        uses: actions/checkout@v4
        with:
          path: data-repo

      - name: Checkout Generator Repo
        uses: actions/checkout@v4
        with:
          repository: fionhua/data-records-code
          path: code-repo
          token: ${{ secrets.CODE_REPO_TOKEN }} # Access private repo

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Generator Dependencies
        run: |
          cd code-repo/site_generator
          npm ci

      - name: Build Site
        run: |
          # Copy Data from Data Repo to Generator's input directory
          # We purposefully overwrite any mock data in the generator
          cp -r data-repo/data/* code-repo/site_generator/data/
          
          cd code-repo/site_generator
          node build.js

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: code-repo/site_generator/public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
